function corner = FAST_12(img,threshold_percentage)


corners = zeros(size(img,1),size(img,2));
tic
for i = 4 : (size(img,1) - 3)
    for j = 4 : (size(img,2) - 3)
       threshold = threshold_percentage * img(i,j);
       I_pos = img(i,j) - threshold; 
       I_neg = img(i,j) + threshold;
       if I_pos>img(i-3,j) || I_neg<img(i-3,j)
           if I_pos>img(i,j+3) || I_neg<img(i,j+3)
               if I_pos>img(i+3,j) || I_neg<img(i+3,j)
                   if (I_pos>img(i-3,j-1)&&...
                           I_pos>img(i-3,j+1)&&...
                           I_pos>img(i-2,j+2)&&...
                           I_pos>img(i-1,j+3)&&...
                           I_pos>img(i+1,j+3)&&...
                           I_pos>img(i+2,j+2)&&...
                           I_pos>img(i+3,j+1)&&...
                           I_pos>img(i+3,j-1))||...
                           (I_neg<img(i-3,j-1)&&...
                           I_neg<img(i-3,j+1)&&...
                           I_neg<img(i-2,j+2)&&...
                           I_neg<img(i-1,j+3)&&...
                           I_neg<img(i+1,j+3)&&...
                           I_neg<img(i+2,j+2)&&...
                           I_neg<img(i+3,j+1)&&...
                           I_neg<img(i+3,j-1))
                       corners(i,j) = 1;
                   end
               end
           end
       elseif I_pos>img(i,j+3) || I_neg<img(i,j+3)
           if I_pos>img(i+3,j) || I_neg<img(i+3,j)
               if I_pos>img(i,j-3) || I_neg<img(i,j-3)
                   if (I_pos>img(i-1,j+3)&&...
                           I_pos>img(i+1,j+3)&&...
                           I_pos>img(i+2,j+2)&&...
                           I_pos>img(i+3,j+1)&&...
                           I_pos>img(i+3,j-1)&&...
                           I_pos>img(i+2,j-2)&&...
                           I_pos>img(i+1,j-3)&&...
                           I_pos>img(i-1,j-3))||...
                           (I_neg<img(i-1,j+3)&&...
                           I_neg<img(i+1,j+3)&&...
                           I_neg<img(i+2,j+2)&&...
                           I_neg<img(i+3,j+1)&&...
                           I_neg<img(i+3,j-1)&&...
                           I_neg<img(i+2,j-2)&&...
                           I_neg<img(i+1,j-3)&&...
                           I_neg<img(i-1,j-3))
                       corners(i,j) = 1;
                   end
               end
           end
       elseif I_pos>img(i+3,j) || I_neg<img(i+3,j)
           if I_pos>img(i,j-3) || I_neg<img(i,j-3)
               if I_pos>img(i-3,j) || I_neg<img(i-3,j)
                   if (I_pos>img(i+3,j+1)&&...
                           I_pos>img(i+3,j-1)&&...
                           I_pos>img(i+2,j-2)&&...
                           I_pos>img(i+1,j-3)&&...
                           I_pos>img(i-1,j-3)&&...
                           I_pos>img(i-2,j-2)&&...
                           I_pos>img(i-3,j-1)&&...
                           I_pos>img(i-3,j+1))||...
                           (I_neg<img(i+3,j+1)&&...
                           I_neg<img(i+3,j-1)&&...
                           I_neg<img(i+2,j-2)&&...
                           I_neg<img(i+1,j-3)&&...
                           I_neg<img(i-1,j-3)&&...
                           I_neg<img(i-2,j-2)&&...
                           I_neg<img(i-3,j-1)&&...
                           I_neg<img(i-3,j+1))
                       corners = 1;
                   end
               end
           end
       elseif I_pos>img(i,j-3) || I_neg<img(i,j-3)
           if I_pos>img(i-3,j) || I_neg<img(i-3,j)
               if I_pos>img(i,j+3) || I_neg<img(i,j+3)
                   if (I_pos>img(i+1,j-3)&&...
                           I_pos>img(i-1,j-3)&&...
                           I_pos>img(i-2,j-2)&&...
                           I_pos>img(i-3,j-1)&&...
                           I_pos>img(i-3,j+1)&&...
                           I_pos>img(i-2,j+2)&&... 
                           I_pos>img(i-1,j+3)&&...
                           I_pos>img(i+1,j+3))||...
                           (I_neg<img(i+1,j-3)&&...
                           I_neg<img(i-1,j-3)&&...
                           I_neg<img(i-2,j-2)&&...
                           I_neg<img(i-3,j-1)&&...
                           I_neg<img(i-3,j+1)&&...
                           I_neg<img(i-2,j+2)&&... 
                           I_neg<img(i-1,j+3)&&...
                           I_neg<img(i+1,j+3))
                       corners(i,j) = 1;
                   end
               end
           end
       end
    end
end
[corner_y,corner_x] = find(corners);
corner = [corner_y corner_x];
end